### ISSUE TITLE
ModuleNotFoundError: No module named 'pip.utils'

### ISSUE THREAD

**Issue by JayFoxRox** [nbeaver/pip_file_lookup#2]
```
Traceback (most recent call last):
  File "./pip_file_lookup.py", line 76, in <module>
    for dist in packages_with_path(args.path):
  File "./pip_file_lookup.py", line 11, in packages_with_path
    import pip.utils
ModuleNotFoundError: No module named 'pip.utils'
```

Arch Linux latest packages at time of writing.

**Comment by nbeaver** [comment]
Hm, it looks like `pip` has made some breaking changes in version 10.

https://github.com/pypa/pip/pull/4700

https://github.com/pypa/pip/commit/95bcf8c5f6394298035a7332c441868f3b0169f4

https://github.com/pypa/pip/issues/5154

https://groups.google.com/forum/#!msg/pypa-dev/JVTfS6ZdAuM/ho4KMzkHAwAJ

https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html

https://mail.python.org/pipermail/distutils-sig/2017-October/031652.html

I'm not sure if it will be possible to accomplish this without using `pip`'s internal API, so this might need to become a pull request to the `pip` project rather than a standalone script.

**Comment by nbeaver** [comment]
I think this might be patched now.

https://github.com/nbeaver/pip_file_lookup/commit/b53a7d2e86d9e829ad5fcc807689a82d732759be

**Comment by HaleTom** [comment]
It works for me as:

```
from pip._internal.utils.misc import get_installed_distributions

MYPATH=sys.argv[1]
for dist in get_installed_distributions():
```

**Comment by nbeaver** [comment]
@HaleTom That's [what the script does now](https://github.com/nbeaver/pip_file_lookup/blob/0b253c4d28c18153e27dc1591888f60732d9f0d7/pip_file_lookup.py#L14). Is it not working for you?

**Comment by nbeaver** [comment]
If anyone on the new version of pip can confirm the fix, I'll close this bug. I would like to try to get this functionality folded into pip, though. Since it uses the `pip._internal` module, breaking changes could happen again with no warning.

**Comment by jayvdb** [comment]
https://github.com/sarugaku/pip-shims and https://github.com/di/pip-api to the rescue.
