### ISSUE TITLE
Clarify support for relative path

### ISSUE THREAD

**Issue by JayFoxRox** [nbeaver/pip_file_lookup#3]
[Your stackoverflow response](https://stackoverflow.com/questions/33483818/how-to-find-which-pip-package-owns-a-file) also suggests that this tool is more powerful, but this projects README is not explicit about still supporting relative path. Please clarify in README, as I'm currently unsure if giving a relative path works or not.

---

(Edit:)

Just to clarify: by relative path I meant an incomplete path. So regardless of path its ran from it would also find `requests/__init__.py` because it would scan *all* paths which end in this name.

Unless this tool is not meant for this sort of action (and there's a better tool).
This further shows this tool needs more documentation in README imo.

**Comment by nbeaver** [comment]
Right now it is absolute paths only. I think it would be possible to add support for relative paths without too much trouble, however.

**Comment by nbeaver** [comment]
I've added support for a single relative path based on the current working directory. I think the incomplete path matching is an interesting idea, since it would make this tool behave more like `locate`, but the implementation would be a little tricky because of things like system-dependent path delimiters. I agree that full pattern matching / globbing / regular expressions would be more powerful, but I don't plan to implement it because the current functionality is sufficient for my needs.
